<?php
// THIS FILE IS AUTOGENERATED, PLEASE DON'T EDIT IT DIRECTLY

return array(
	"General settings" => array(
		__( "General settings", 'yith-woocommerce-subscription' ),
	),
	"Date" => array(
		__( "Date", 'yith-woocommerce-subscription' ),
	),
	"Customer" => array(
		__( "Customer", 'yith-woocommerce-subscription' ),
	),
	"Status" => array(
		__( "Status", 'yith-woocommerce-subscription' ),
	),
	"Product name" => array(
		__( "Product name", 'yith-woocommerce-subscription' ),
	),
	"Shipping" => array(
		__( "Shipping", 'yith-woocommerce-subscription' ),
	),
	"Guest" => array(
		__( "Guest", 'yith-woocommerce-subscription' ),
	),
	"All products" => array(
		__( "All products", 'yith-woocommerce-subscription' ),
	),
	"Your box" => array(
		__( "Your box", 'yith-woocommerce-subscription' ),
	),
	"Total paid" => array(
		__( "Total paid", 'yith-woocommerce-subscription' ),
	),
	"Email" => array(
		__( "Email", 'yith-woocommerce-subscription' ),
	),
	"Active subscriptions" => array(
		__( "Active subscriptions", 'yith-woocommerce-subscription' ),
	),
	"Cancelled subscriptions" => array(
		__( "Cancelled subscriptions", 'yith-woocommerce-subscription' ),
	),
	"Product" => array(
		__( "Product", 'yith-woocommerce-subscription' ),
	),
	"Subscribers" => array(
		__( "Subscribers", 'yith-woocommerce-subscription' ),
	),
	"MRR" => array(
		__( "MRR", 'yith-woocommerce-subscription' ),
	),
	"Subscription #" => array(
		__( "Subscription #", 'yith-woocommerce-subscription' ),
	),
	"Conversion date" => array(
		__( "Conversion date", 'yith-woocommerce-subscription' ),
	),
	"New trials" => array(
		__( "New trials", 'yith-woocommerce-subscription' ),
	),
	"Add subscription table column" => array(
		__( "Add subscription table column", 'yith-woocommerce-subscription' ),
	),
	"Add subscription table price" => array(
		__( "Add subscription table price", 'yith-woocommerce-subscription' ),
	),
	"Price settings" => array(
		__( "Price settings", 'yith-woocommerce-subscription' ),
	),
	"Billing period settings" => array(
		__( "Billing period settings", 'yith-woocommerce-subscription' ),
	),
	"Fee settings" => array(
		__( "Fee settings", 'yith-woocommerce-subscription' ),
	),
	"The fee wil be displayed" => array(
		__( "The fee wil be displayed", 'yith-woocommerce-subscription' ),
	),
	"There is no fee" => array(
		__( "There is no fee", 'yith-woocommerce-subscription' ),
	),
	"Trial settings" => array(
		__( "Trial settings", 'yith-woocommerce-subscription' ),
	),
	"The trial text wil be displayed" => array(
		__( "The trial text wil be displayed", 'yith-woocommerce-subscription' ),
	),
	"There is no trial" => array(
		__( "There is no trial", 'yith-woocommerce-subscription' ),
	),
	"Billing period inline" => array(
		__( "Billing period inline", 'yith-woocommerce-subscription' ),
	),
	"Billing period on top" => array(
		__( "Billing period on top", 'yith-woocommerce-subscription' ),
	),
	"Billing period on bottom" => array(
		__( "Billing period on bottom", 'yith-woocommerce-subscription' ),
	),
	"Show" => array(
		__( "Show", 'yith-woocommerce-subscription' ),
	),
	"Type to search for a product" => array(
		__( "Type to search for a product", 'yith-woocommerce-subscription' ),
	),
	"Type to search for a variation" => array(
		__( "Type to search for a variation", 'yith-woocommerce-subscription' ),
	),
	"No data for the selected date range" => array(
		__( "No data for the selected date range", 'yith-woocommerce-subscription' ),
	),
	"Settings" => array(
		__( "Settings", 'yith-woocommerce-subscription' ),
	),
	"Show image" => array(
		__( "Show image", 'yith-woocommerce-subscription' ),
	),
	"Hide image" => array(
		__( "Hide image", 'yith-woocommerce-subscription' ),
	),
	"Show list" => array(
		__( "Show list", 'yith-woocommerce-subscription' ),
	),
	"Hide list" => array(
		__( "Hide list", 'yith-woocommerce-subscription' ),
	),
	"Animated hover effect" => array(
		__( "Animated hover effect", 'yith-woocommerce-subscription' ),
	),
	"Grow" => array(
		__( "Grow", 'yith-woocommerce-subscription' ),
	),
	"Float" => array(
		__( "Float", 'yith-woocommerce-subscription' ),
	),
	"Sink" => array(
		__( "Sink", 'yith-woocommerce-subscription' ),
	),
	"Shrink" => array(
		__( "Shrink", 'yith-woocommerce-subscription' ),
	),
	"Set a transparent background color" => array(
		__( "Set a transparent background color", 'yith-woocommerce-subscription' ),
	),
	"Title font size" => array(
		__( "Title font size", 'yith-woocommerce-subscription' ),
	),
	"Subtitle font size" => array(
		__( "Subtitle font size", 'yith-woocommerce-subscription' ),
	),
	"Show separator between subtitle and title" => array(
		__( "Show separator between subtitle and title", 'yith-woocommerce-subscription' ),
	),
	"Show separator" => array(
		__( "Show separator", 'yith-woocommerce-subscription' ),
	),
	"Hide separator" => array(
		__( "Hide separator", 'yith-woocommerce-subscription' ),
	),
	"Shadow color" => array(
		__( "Shadow color", 'yith-woocommerce-subscription' ),
	),
	"Shadow H offset" => array(
		__( "Shadow H offset", 'yith-woocommerce-subscription' ),
	),
	"Shadow V offset" => array(
		__( "Shadow V offset", 'yith-woocommerce-subscription' ),
	),
	"Shadow blur" => array(
		__( "Shadow blur", 'yith-woocommerce-subscription' ),
	),
	"Shadow spread" => array(
		__( "Shadow spread", 'yith-woocommerce-subscription' ),
	),
	"View all" => array(
		__( "View all", 'yith-woocommerce-subscription' ),
	),
	"Total" => array(
		__( "Total", 'yith-woocommerce-subscription' ),
	),
	"Reason" => array(
		__( "Reason", 'yith-woocommerce-subscription' ),
	),
	"Products" => array(
		__( "Products", 'yith-woocommerce-subscription' ),
	),
	"Name" => array(
		__( "Name", 'yith-woocommerce-subscription' ),
	),
	"End Date" => array(
		__( "End Date", 'yith-woocommerce-subscription' ),
	),
	"Net" => array(
		__( "Net", 'yith-woocommerce-subscription' ),
	),
	"Single product" => array(
		__( "Single product", 'yith-woocommerce-subscription' ),
	),
	"All variations" => array(
		__( "All variations", 'yith-woocommerce-subscription' ),
	),
	"Single variation" => array(
		__( "Single variation", 'yith-woocommerce-subscription' ),
	),
	"Border radius" => array(
		__( "Border radius", 'yith-woocommerce-subscription' ),
	),
	"No effects" => array(
		__( "No effects", 'yith-woocommerce-subscription' ),
	),
	"Background color" => array(
		__( "Background color", 'yith-woocommerce-subscription' ),
	),
	"Border color" => array(
		__( "Border color", 'yith-woocommerce-subscription' ),
	),
	"Titles bar" => array(
		__( "Titles bar", 'yith-woocommerce-subscription' ),
	),
	"Subtitle text" => array(
		__( "Subtitle text", 'yith-woocommerce-subscription' ),
	),
	"Number of plans" => array(
		__( "Number of plans", 'yith-woocommerce-subscription' ),
	),
	"Show fee text?" => array(
		__( "Show fee text?", 'yith-woocommerce-subscription' ),
	),
	"Show trial text?" => array(
		__( "Show trial text?", 'yith-woocommerce-subscription' ),
	),
	"< Back to main report" => array(
		__( "< Back to main report", 'yith-woocommerce-subscription' ),
	),
	"Total net sale" => array(
		__( "Total net sale", 'yith-woocommerce-subscription' ),
	),
	"New subscriptions" => array(
		__( "New subscriptions", 'yith-woocommerce-subscription' ),
	),
	"Net sales of new subscriptions" => array(
		__( "Net sales of new subscriptions", 'yith-woocommerce-subscription' ),
	),
	"Renewal orders" => array(
		__( "Renewal orders", 'yith-woocommerce-subscription' ),
	),
	"Net sales of renewed subscriptions" => array(
		__( "Net sales of renewed subscriptions", 'yith-woocommerce-subscription' ),
	),
	"Trial conversions" => array(
		__( "Trial conversions", 'yith-woocommerce-subscription' ),
	),
	"MRR (monthly recurring revenue)" => array(
		__( "MRR (monthly recurring revenue)", 'yith-woocommerce-subscription' ),
	),
	"ARR (annual recurring revenue)" => array(
		__( "ARR (annual recurring revenue)", 'yith-woocommerce-subscription' ),
	),
	"Renewed subscriptions" => array(
		__( "Renewed subscriptions", 'yith-woocommerce-subscription' ),
	),
	"Top subscription products" => array(
		__( "Top subscription products", 'yith-woocommerce-subscription' ),
	),
	"Products dashboard" => array(
		__( "Products dashboard", 'yith-woocommerce-subscription' ),
	),
	"Subscribers dashboard" => array(
		__( "Subscribers dashboard", 'yith-woocommerce-subscription' ),
	),
	"Subscription products" => array(
		__( "Subscription products", 'yith-woocommerce-subscription' ),
	),
	"General color settings" => array(
		__( "General color settings", 'yith-woocommerce-subscription' ),
	),
	"Box shadow" => array(
		__( "Box shadow", 'yith-woocommerce-subscription' ),
	),
	"Subscription plan" => array(
		__( "Subscription plan", 'yith-woocommerce-subscription' ),
	),
	"Subscription plans" => array(
		__( "Subscription plans", 'yith-woocommerce-subscription' ),
	),
	"Subscription price" => array(
		__( "Subscription price", 'yith-woocommerce-subscription' ),
	),
	"Add subscription price inside the subscription plan" => array(
		__( "Add subscription price inside the subscription plan", 'yith-woocommerce-subscription' ),
	),
	"Top subscribers" => array(
		__( "Top subscribers", 'yith-woocommerce-subscription' ),
	),
	"Latest lost subscribers" => array(
		__( "Latest lost subscribers", 'yith-woocommerce-subscription' ),
	),
	"Subscriptions list" => array(
		__( "Subscriptions list", 'yith-woocommerce-subscription' ),
	),
	"Tax" => array(
		__( "Tax", 'yith-woocommerce-subscription' ),
	),
	"%s product" => array(
		_n( "%s product", "%s products", 1, 'yith-woocommerce-subscription' ),
		_n( "%s product", "%s products", 2, 'yith-woocommerce-subscription' ),
	),
	"Discount" => array(
		__( "Discount", 'yith-woocommerce-subscription' ),
	),
	"Order details" => array(
		__( "Order details", 'yith-woocommerce-subscription' ),
	),
	"Save box" => array(
		__( "Save box", 'yith-woocommerce-subscription' ),
	),
	"Proceed to Checkout" => array(
		__( "Proceed to Checkout", 'yith-woocommerce-subscription' ),
	),
	"Back" => array(
		__( "Back", 'yith-woocommerce-subscription' ),
	),
	"Rated %s out of 5" => array(
		__( "Rated %s out of 5", 'yith-woocommerce-subscription' ),
	),
	"You cannot add this product to the box because it is out of stock." => array(
		__( "You cannot add this product to the box because it is out of stock.", 'yith-woocommerce-subscription' ),
	),
	"You cannot add more than %s to the box because there isn't enough stock." => array(
		__( "You cannot add more than %s to the box because there isn't enough stock.", 'yith-woocommerce-subscription' ),
	),
	"Please select at least %s product(s) for this step" => array(
		__( "Please select at least %s product(s) for this step", 'yith-woocommerce-subscription' ),
	),
	"Please add at least one product to this box" => array(
		__( "Please add at least one product to this box", 'yith-woocommerce-subscription' ),
	),
	"Minimum amount required: %s" => array(
		__( "Minimum amount required: %s", 'yith-woocommerce-subscription' ),
	),
	"You can add a max of %s product(s) in this step" => array(
		__( "You can add a max of %s product(s) in this step", 'yith-woocommerce-subscription' ),
	),
	"You can add a max of %s unit(s) of this product" => array(
		__( "You can add a max of %s unit(s) of this product", 'yith-woocommerce-subscription' ),
	),
	"Maximum amount allowed: %s" => array(
		__( "Maximum amount allowed: %s", 'yith-woocommerce-subscription' ),
	),
	"Subscription Box mini-cart items edit labeledit" => array(
		_x( "edit", "Subscription Box mini-cart items edit label", 'yith-woocommerce-subscription' ),
	),
	"Subscription Box mini-cart icon altMini Cart icon" => array(
		_x( "Mini Cart icon", "Subscription Box mini-cart icon alt", 'yith-woocommerce-subscription' ),
	),
	"Subscription Box mini-cart labelBox price:" => array(
		_x( "Box price:", "Subscription Box mini-cart label", 'yith-woocommerce-subscription' ),
	),
	"Subscription Box mini-cart titleYour box" => array(
		_x( "Your box", "Subscription Box mini-cart title", 'yith-woocommerce-subscription' ),
	),
	"Box product cart quantity labelQuantity" => array(
		_x( "Quantity", "Box product cart quantity label", 'yith-woocommerce-subscription' ),
	),
	"Subscription box button labelNext" => array(
		_x( "Next", "Subscription box button label", 'yith-woocommerce-subscription' ),
	),
	"Quick view product tab labelDescription" => array(
		_x( "Description", "Quick view product tab label", 'yith-woocommerce-subscription' ),
	),
	"Quick view product tab labelAdditional information" => array(
		_x( "Additional information", "Quick view product tab label", 'yith-woocommerce-subscription' ),
	),
	"Quick view product tab labelReviews (%s)" => array(
		_x( "Reviews (%s)", "Quick view product tab label", 'yith-woocommerce-subscription' ),
	),
);